CI: cleanup

diff --git a/.github/workflows/network-manager.yml b/.github/workflows/network-manager.yml
--- a/.github/workflows/network-manager.yml
+++ b/.github/workflows/network-manager.yml
@@ -33,7 +33,6 @@ jobs:
       # it's needed (will be auto-loaded) by routing.test_vrf_basic
       - name: Install dependencies
         run: |
-          sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
           sudo apt update
           sudo apt install autopkgtest ubuntu-dev-tools devscripts openvswitch-switch linux-modules-extra-$(uname -r)
       - name: Prepare test
@@ -41,6 +40,7 @@ jobs:
           pull-lp-source netplan.io
           cp -r netplan.io-*/debian .
           rm -r debian/patches/  # clear any distro patches
+          sed -i 's|rm debian/tmp/lib/netplan/generate|# DELETED|' debian/rules
           echo "3.0 (native)" > debian/source/format  # force native build
           TAG=$(git describe --tags $(git rev-list --tags --max-count=1))  # find latest (stable) tag
           REV=$(git rev-parse --short HEAD)  # get current git revision
@@ -54,7 +54,7 @@ jobs:
         with:
           docker-image: ubuntu:mantic
           buildpackage-opts: --build=binary --no-sign
-          extra-build-deps: python3-cffi libpython3-dev
+          #extra-build-deps: python3-cffi libpython3-dev
       # work around LP: #1878225 as fallback
       - name: Preparing autopkgtest-build-lxd
         run: |
@@ -64,4 +64,5 @@ jobs:
         run: |
           # using --setup-commands temporarily to install:
           # cmocka/pytest/rich/ethtool until they become proper test-deps
-          sudo autopkgtest -U debian/artifacts/*.deb network-manager --apt-pocket=proposed=src:network-manager -- lxd autopkgtest/ubuntu/mantic/amd64 || test $? -eq 2  # allow for skipped tests (exit code = 2)
+          sudo autopkgtest -U debian/artifacts/*.deb \
+            network-manager --apt-pocket=proposed=src:network-manager -- lxd autopkgtest/ubuntu/mantic/amd64 || test $? -eq 2  # allow for skipped tests (exit code = 2)
